//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.05 at 04:09:16 PM EDT 
//


package com.wex.poc.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organizationId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="payableId" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="deliveryMethod" type="{}stringVMaxSize5"/>
 *         &lt;element name="numberOfAuthorizationsAllowed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="amountOfAuthorizationsAllowed" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organizationId",
    "payableId",
    "amount",
    "deliveryMethod",
    "numberOfAuthorizationsAllowed",
    "amountOfAuthorizationsAllowed"
})
@XmlRootElement(name = "Vpayable")
public class Vpayable {

    protected double organizationId;
    protected double payableId;
    protected double amount;
    @XmlElement(required = true)
    protected String deliveryMethod;
    protected int numberOfAuthorizationsAllowed;
    protected double amountOfAuthorizationsAllowed;

    /**
     * Gets the value of the organizationId property.
     * 
     */
    public double getOrganizationId() {
        return organizationId;
    }

    /**
     * Sets the value of the organizationId property.
     * 
     */
    public void setOrganizationId(double value) {
        this.organizationId = value;
    }

    /**
     * Gets the value of the payableId property.
     * 
     */
    public double getPayableId() {
        return payableId;
    }

    /**
     * Sets the value of the payableId property.
     * 
     */
    public void setPayableId(double value) {
        this.payableId = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the deliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMethod() {
        return deliveryMethod;
    }

    /**
     * Sets the value of the deliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMethod(String value) {
        this.deliveryMethod = value;
    }

    /**
     * Gets the value of the numberOfAuthorizationsAllowed property.
     * 
     */
    public int getNumberOfAuthorizationsAllowed() {
        return numberOfAuthorizationsAllowed;
    }

    /**
     * Sets the value of the numberOfAuthorizationsAllowed property.
     * 
     */
    public void setNumberOfAuthorizationsAllowed(int value) {
        this.numberOfAuthorizationsAllowed = value;
    }

    /**
     * Gets the value of the amountOfAuthorizationsAllowed property.
     * 
     */
    public double getAmountOfAuthorizationsAllowed() {
        return amountOfAuthorizationsAllowed;
    }

    /**
     * Sets the value of the amountOfAuthorizationsAllowed property.
     * 
     */
    public void setAmountOfAuthorizationsAllowed(double value) {
        this.amountOfAuthorizationsAllowed = value;
    }

}
